[build]
  command    = "pnpm install --frozen-lockfile && pnpm turbo run build --filter=web-mfe-auth"
  publish    = "apps/web-mfe-auth/dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
